# Generated by Django 4.2.16 on 2026-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField(help_text="Python code. Must define a function named 'run(db)' that returns a dict.\nThe 'db' argument gives access to Django ORM (CanonicalReading, Sensor, Site).\nReturn dict keys: 'title', 'labels', 'datasets', 'summary' (optional), 'table' (optional).\nExample:\ndef run(db):\n    from django.utils import timezone\n    from datetime import timedelta\n    qs = db.CanonicalReading.objects.filter(\n        pollutant='PM25', is_duplicate=False,\n        original_ts__gte=timezone.now() - timedelta(days=7)\n    ).values_list('original_ts', 'raw_value')[:200]\n    return {\n        'title': 'Last 7 days PM2.5',\n        'labels': [str(r[0]) for r in qs],\n        'datasets': [{'label': 'PM2.5', 'data': [r[1] for r in qs]}]\n    }")),
                ('run_mode', models.CharField(choices=[('CONTINUOUS', 'Continuous (auto-refresh)'), ('CACHED', 'Cached (run once)')], default='CACHED', max_length=20)),
                ('chart_type', models.CharField(choices=[('TIMESERIES', 'Time Series'), ('BAR', 'Bar Chart'), ('TABLE', 'Data Table'), ('METRIC', 'Single Metric'), ('SCATTER', 'Scatter Plot')], default='TIMESERIES', max_length=20)),
                ('interval_minutes', models.PositiveIntegerField(default=60, help_text='For CONTINUOUS mode: re-run every N minutes.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order on the analysis page.')),
                ('cached_result', models.TextField(blank=True, help_text='JSON result from last successful run.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('run_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analysis Script',
                'verbose_name_plural': 'Analysis Scripts',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_rows_public', models.PositiveIntegerField(default=500, help_text='Max rows any unauthenticated or PUBLIC-role user can download.')),
                ('max_rows_researcher', models.PositiveIntegerField(default=50000, help_text='Max rows a RESEARCHER can download per request.')),
                ('max_rows_admin', models.PositiveIntegerField(default=500000, help_text='Max rows an ADMIN or MAINTAINER can download per request.')),
                ('public_days_limit', models.PositiveIntegerField(default=7, help_text='Public users can only download the last N days of data.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Download Configuration',
                'verbose_name_plural': 'Download Configuration',
            },
        ),
    ]
