# Generated by Django 4.2.16 on 2026-05-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibration_date', models.DateField()),
                ('method', models.CharField(blank=True, help_text='e.g. co-location with reference instrument', max_length=200)),
                ('slope_before', models.FloatField(blank=True, null=True)),
                ('intercept_before', models.FloatField(blank=True, null=True)),
                ('slope_after', models.FloatField(blank=True, null=True)),
                ('intercept_after', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-calibration_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('REPAIR', 'Repair'), ('CALIBRATION', 'Calibration'), ('POWER_ISSUE', 'Power Issue'), ('CONNECTIVITY_ISSUE', 'Connectivity Issue'), ('RELOCATION', 'Relocation'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(help_text='Decimal degrees (WGS 84). Positive = North.')),
                ('longitude', models.FloatField(help_text='Decimal degrees (WGS 84). Positive = East.')),
                ('elevation_m', models.FloatField(blank=True, help_text='Elevation above sea level (m).', null=True)),
                ('population_estimate', models.PositiveIntegerField(blank=True, help_text='Estimated population within ~1 km of this site.', null=True)),
                ('land_use_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('AGRICULTURAL', 'Agricultural'), ('FOREST', 'Forest'), ('URBAN', 'Urban'), ('INDUSTRIAL', 'Industrial'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], default='RESIDENTIAL', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(help_text='e.g. 8143, 8144', max_length=50)),
                ('manufacturer', models.CharField(default='Particles Plus', max_length=100)),
                ('is_indoor', models.BooleanField(default=False, help_text='True for indoor deployments.')),
                ('power_type', models.CharField(choices=[('GRID', 'Grid'), ('SOLAR', 'Solar'), ('BATTERY', 'Battery'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('connectivity_type', models.CharField(choices=[('WIFI', 'Wi-Fi'), ('CELLULAR', 'Cellular'), ('LORA', 'LoRa'), ('MANUAL', 'Manual upload'), ('UNKNOWN', 'Unknown')], default='WIFI', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Under Maintenance'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=20)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True)),
                ('installation_notes', models.TextField(blank=True)),
                ('calibration_field_notes', models.TextField(blank=True, help_text='Free-text notes about calibration.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='sensors.site')),
            ],
            options={
                'ordering': ['site__name', 'serial_number'],
            },
        ),
    ]
