# Generated by Django 4.2.16 on 2026-05-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Absolute path to the saved upload on disk.', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_saved', models.PositiveIntegerField(default=0)),
                ('records_duplicate', models.PositiveIntegerField(default=0)),
                ('records_error', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('sensor', models.ForeignKey(blank=True, help_text='Pre-selected sensor (SensorUploadView). Null for the generic upload view.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='sensors.sensor')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
