# Generated by Django 4.2.16 on 2026-05-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_ingestionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='r2_key',
            field=models.CharField(blank=True, help_text='R2 object key for the uploaded CSV (e.g. uploads/42/data.csv).', max_length=500),
        ),
    ]
