# Generated by Django 4.2.16 on 2026-05-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationExposureEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.CharField(max_length=100)),
                ('estimate_date', models.DateField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('pm25_mean_ugm3', models.FloatField(blank=True, null=True)),
                ('pm25_completeness', models.FloatField(blank=True, help_text='0–1', null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('pop_above_who_24h', models.PositiveIntegerField(blank=True, help_text='Estimated people exposed above WHO 24h guideline (15 µg/m³).', null=True)),
                ('confidence', models.CharField(choices=[('HIGH', 'High (sensor within 20 km, >80% data completeness)'), ('MEDIUM', 'Medium (sensor within 50 km, 50–80% completeness)'), ('LOW', 'Low (sensor >50 km away or <50% completeness)'), ('NONE', 'No estimate available')], default='NONE', max_length=10)),
                ('methodology_note', models.TextField(default='Nearest-sensor assignment. Air quality at sensor location assigned to district. This is a simplified spatial proxy — actual exposure depends on microenvironments, indoor time, and local sources not captured by a single sensor.')),
            ],
            options={
                'ordering': ['-estimate_date', 'district'],
            },
        ),
    ]
