# Generated by Django 4.2.16 on 2026-05-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('exposure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationexposureestimate',
            name='nearest_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposure_estimates', to='sensors.site'),
        ),
        migrations.AlterUniqueTogether(
            name='populationexposureestimate',
            unique_together={('district', 'estimate_date')},
        ),
    ]
