# Generated by Django 4.2.16 on 2026-05-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Belauri Outdoor Sensor'", max_length=100)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('SENSOR', 'Sensor (POST readings)'), ('RESEARCHER', 'Researcher (GET data)'), ('ADMIN', 'Admin (full access)')], default='SENSOR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
