# Generated by Django 4.2.16 on 2026-05-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_initial'),
        ('api', '0003_apikey_hashed_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='If set, this key may only POST readings for this sensor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='sensors.sensor'),
        ),
    ]
