# Generated by Django 4.2.16 on 2026-05-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_ts', models.DateTimeField(db_index=True, help_text='Timestamp as reported by the sensor (timezone-aware).')),
                ('received_ts', models.DateTimeField(auto_now_add=True, help_text='When this record was ingested into our system.')),
                ('timezone', models.CharField(default='Asia/Kathmandu', help_text="IANA timezone string for the sensor's deployment location.", max_length=50)),
                ('interval_seconds', models.IntegerField(blank=True, help_text='Reporting interval in seconds (e.g. 60 for 1-minute data).', null=True)),
                ('pollutant', models.CharField(choices=[('PM1', 'PM1 (µg/m³)'), ('PM25', 'PM2.5 (µg/m³)'), ('PM4', 'PM4 (µg/m³)'), ('PM10', 'PM10 (µg/m³)'), ('CO2', 'CO₂ (ppm)'), ('TVOC', 'Total VOC (mg/m³)'), ('TEMP', 'Temperature (°C)'), ('RH', 'Relative Humidity (%)'), ('BARO', 'Barometric Pressure (inHg)'), ('NC05', 'NC 0.5 (#/cm³)'), ('NC1', 'NC 1.0 (#/cm³)'), ('NC25', 'NC 2.5 (#/cm³)')], db_index=True, max_length=10)),
                ('unit', models.CharField(help_text='e.g. µg/m³, ppm, °C, %, inHg, #/cm³', max_length=20)),
                ('raw_value', models.FloatField(blank=True, help_text='Value exactly as received from the sensor. NEVER overwrite.', null=True)),
                ('cleaned_value', models.FloatField(blank=True, help_text='QC-corrected value. raw_value is always preserved separately.', null=True)),
                ('is_indoor', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('LIVE_API', 'Live API'), ('CSV_UPLOAD', 'CSV Upload'), ('BATCH_UPLOAD', 'Batch Upload'), ('MANUAL', 'Manual Entry'), ('EXTERNAL', 'External')], default='CSV_UPLOAD', max_length=20)),
                ('quality_flag', models.CharField(choices=[('GOOD', 'Good'), ('SUSPECT', 'Suspect'), ('BAD', 'Bad'), ('MISSING', 'Missing'), ('UNVALIDATED', 'Unvalidated')], db_index=True, default='UNVALIDATED', max_length=15)),
                ('flag_reason', models.TextField(blank=True, help_text='Human-readable reason for SUSPECT/BAD flag.')),
                ('is_duplicate', models.BooleanField(default=False, help_text='True if this reading is a duplicate. Kept for audit trail.')),
            ],
            options={
                'ordering': ['-original_ts'],
            },
        ),
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('pollutant', models.CharField(choices=[('PM1', 'PM1 (µg/m³)'), ('PM25', 'PM2.5 (µg/m³)'), ('PM4', 'PM4 (µg/m³)'), ('PM10', 'PM10 (µg/m³)'), ('CO2', 'CO₂ (ppm)'), ('TVOC', 'Total VOC (mg/m³)'), ('TEMP', 'Temperature (°C)'), ('RH', 'Relative Humidity (%)'), ('BARO', 'Barometric Pressure (inHg)'), ('NC05', 'NC 0.5 (#/cm³)'), ('NC1', 'NC 1.0 (#/cm³)'), ('NC25', 'NC 2.5 (#/cm³)')], max_length=10)),
                ('is_indoor', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of valid readings.')),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('p25', models.FloatField(blank=True, null=True)),
                ('p75', models.FloatField(blank=True, null=True)),
                ('p95', models.FloatField(blank=True, null=True)),
                ('completeness', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('LIVE_API', 'Live API'), ('CSV_UPLOAD', 'CSV Upload'), ('BATCH_UPLOAD', 'Batch Upload'), ('MANUAL', 'Manual Entry'), ('EXTERNAL', 'External (e.g. OpenAQ)')], max_length=20)),
                ('source_file', models.CharField(blank=True, help_text='Original filename or URL.', max_length=500)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(help_text='e.g. BelauriCSVConverter', max_length=100)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=10)),
                ('records_attempted', models.PositiveIntegerField(default=0)),
                ('records_saved', models.PositiveIntegerField(default=0)),
                ('records_duplicate', models.PositiveIntegerField(default=0)),
                ('records_error', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readings.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
