# Generated by Django 4.2.16 on 2026-05-28 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionlog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='sensors.sensor'),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='sensors.site'),
        ),
        migrations.AddField(
            model_name='canonicalreading',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='readings.dataset'),
        ),
        migrations.AddField(
            model_name='canonicalreading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='sensors.sensor'),
        ),
        migrations.AddField(
            model_name='canonicalreading',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='sensors.site'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyaggregate',
            unique_together={('sensor', 'date', 'pollutant')},
        ),
        migrations.AddIndex(
            model_name='canonicalreading',
            index=models.Index(fields=['sensor', 'pollutant', 'original_ts'], name='readings_ca_sensor__41f6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalreading',
            index=models.Index(fields=['site', 'original_ts'], name='readings_ca_site_id_46600a_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalreading',
            index=models.Index(fields=['pollutant', 'quality_flag'], name='readings_ca_polluta_c11060_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalreading',
            constraint=models.UniqueConstraint(condition=models.Q(('is_duplicate', False)), fields=('sensor', 'pollutant', 'original_ts'), name='unique_reading_per_sensor_pollutant_ts'),
        ),
    ]
