# Generated by Django 4.2.16 on 2026-05-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_initial'),
        ('readings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalreading',
            name='pollutant',
            field=models.CharField(choices=[('PM1', 'PM1 (µg/m³)'), ('PM25', 'PM2.5 (µg/m³)'), ('PM4', 'PM4 (µg/m³)'), ('PM10', 'PM10 (µg/m³)'), ('CO2', 'CO₂ (ppm)'), ('CO', 'CO (ppm)'), ('SO2', 'SO₂ (µg/m³)'), ('O3', 'O₃ (µg/m³)'), ('NO2', 'NO₂ (µg/m³)'), ('CH2O', 'CH₂O / Formaldehyde (µg/m³)'), ('TVOC', 'Total VOC (mg/m³)'), ('TEMP', 'Temperature (°C)'), ('RH', 'Relative Humidity (%)'), ('BARO', 'Barometric Pressure (inHg)'), ('NC05', 'NC 0.5 (#/cm³)'), ('NC1', 'NC 1.0 (#/cm³)'), ('NC25', 'NC 2.5 (#/cm³)'), ('NC4', 'NC 4.0 (#/cm³)'), ('NC10', 'NC 10.0 (#/cm³)')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyaggregate',
            name='pollutant',
            field=models.CharField(choices=[('PM1', 'PM1 (µg/m³)'), ('PM25', 'PM2.5 (µg/m³)'), ('PM4', 'PM4 (µg/m³)'), ('PM10', 'PM10 (µg/m³)'), ('CO2', 'CO₂ (ppm)'), ('CO', 'CO (ppm)'), ('SO2', 'SO₂ (µg/m³)'), ('O3', 'O₃ (µg/m³)'), ('NO2', 'NO₂ (µg/m³)'), ('CH2O', 'CH₂O / Formaldehyde (µg/m³)'), ('TVOC', 'Total VOC (mg/m³)'), ('TEMP', 'Temperature (°C)'), ('RH', 'Relative Humidity (%)'), ('BARO', 'Barometric Pressure (inHg)'), ('NC05', 'NC 0.5 (#/cm³)'), ('NC1', 'NC 1.0 (#/cm³)'), ('NC25', 'NC 2.5 (#/cm³)'), ('NC4', 'NC 4.0 (#/cm³)'), ('NC10', 'NC 10.0 (#/cm³)')], max_length=10),
        ),
        migrations.CreateModel(
            name='HourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour', models.DateTimeField(db_index=True, help_text='Hour start (UTC, tz-aware).')),
                ('pollutant', models.CharField(choices=[('PM1', 'PM1 (µg/m³)'), ('PM25', 'PM2.5 (µg/m³)'), ('PM4', 'PM4 (µg/m³)'), ('PM10', 'PM10 (µg/m³)'), ('CO2', 'CO₂ (ppm)'), ('CO', 'CO (ppm)'), ('SO2', 'SO₂ (µg/m³)'), ('O3', 'O₃ (µg/m³)'), ('NO2', 'NO₂ (µg/m³)'), ('CH2O', 'CH₂O / Formaldehyde (µg/m³)'), ('TVOC', 'Total VOC (mg/m³)'), ('TEMP', 'Temperature (°C)'), ('RH', 'Relative Humidity (%)'), ('BARO', 'Barometric Pressure (inHg)'), ('NC05', 'NC 0.5 (#/cm³)'), ('NC1', 'NC 1.0 (#/cm³)'), ('NC25', 'NC 2.5 (#/cm³)'), ('NC4', 'NC 4.0 (#/cm³)'), ('NC10', 'NC 10.0 (#/cm³)')], max_length=10)),
                ('is_indoor', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('completeness', models.FloatField(blank=True, help_text='Fraction of expected readings received (0–1).', null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_aggregates', to='sensors.sensor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_aggregates', to='sensors.site')),
            ],
            options={
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['sensor', 'pollutant', 'hour'], name='readings_ho_sensor__11141d_idx')],
                'unique_together': {('sensor', 'hour', 'pollutant')},
            },
        ),
    ]
